### ISSUE TITLE
Deprecation warning due to invalid escape sequences in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [alliefitter/boto3_type_annotations#15]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/ . I have attached the command to compile files that emit this but there are high number of warnings to attach them all to the report.

```
find . -iname '*.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./boto3_type_annotations_with_docs/boto3_type_annotations/pinpoint/client.py:12095: DeprecationWarning: invalid escape sequence \ 
  """
./boto3_type_annotations_with_docs/boto3_type_annotations/pinpoint/client.py:12209: DeprecationWarning: invalid escape sequence \ 
  """
./boto3_type_annotations_with_docs/boto3_type_annotations/dynamodb/service_resource.py:1786: DeprecationWarning: invalid escape sequence \:
  """
./boto3_type_annotations_with_docs/boto3_type_annotations/dynamodb/service_resource.py:2753: DeprecationWarning: invalid escape sequence \:
  """
./boto3_type_annotations_with_docs/boto3_type_annotations/dynamodb/service_resource.py:3429: DeprecationWarning: invalid escape sequence \:
  """
./boto3_type_annotations_with_docs/boto3_type_annotations/dynamodb/service_resource.py:4196: DeprecationWarning: invalid escape sequence \:
```

**Comment by alliefitter** [comment]
This package is no longer maintained. I'd suggest using [boto3-stubs/mypy_boto3](https://github.com/vemel/mypy_boto3_builder). If you have some existing code that's using `boto3_type_annotations`, you can submit a pull request, and if everything looks good. I'll release a new version in PyPI.

**Comment by tirkarthi** [comment]
Thanks, closing then.
