### ISSUE TITLE
Why is the lambda package suffixed with _

### ISSUE THREAD

**Issue by pgilad** [alliefitter/boto3_type_annotations#5]
the lambda package on both type annotation packages is suffixed with `_`, i.e `lambda_`?

Can we rename it to be just `lambda`?

**Comment by alliefitter** [comment]
[According to the PEP8](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles), when a name conflicts with a keyword, you should use a trailing underscore. It makes sense. If you were to do the following...

```
from boto3_type_annotations import lamdba
```

... you'd be replacing the keyword `lambda` with the module `boto3_type_annotations.lambda`. That said, if you **really** wanted to, you could as import it with an alias.

```
from boto3_type_annotations import lambda_ as lambda
```

I would sincerely recommend that you don't do this, though.

**Comment by pgilad** [comment]
Thanks for the explanation!
